### ISSUE TITLE
Fatal error: Uncaught Exception: View file 

### ISSUE THREAD

**Issue by dignityinside** [artemmelnik/flexicms#18]
Some errors after composer install:

`Fatal error: Uncaught Exception: View file <strong>/opt/lampp/htdocs/local_projects/demo/modules/Front/View/index.phtml</strong> does not exist! in /home/dignity/local_projects/demo/flexi/Template/Component.php:56 Stack trace: #0 /home/dignity/local_projects/demo/flexi/Template/View.php(105): Flexi\Template\Component::load('/opt/lampp/htdo...', Array) #1 /home/dignity/local_projects/demo/flexi/Template/Layout.php(86): Flexi\Template\View->render() #2 /home/dignity/local_projects/demo/content/themes/default/main.layout.phtml(6): Flexi\Template\Layout::content() #3 /home/dignity/local_projects/demo/flexi/Template/Component.php(50): include('/home/dignity/l...') #4 /home/dignity/local_projects/demo/flexi/Template/Layout.php(60): Flexi\Template\Component::load('/home/dignity/l...', Array) #5 /home/dignity/local_projects/demo/flexi/Routing/Router.php(71): Flexi\Template\Layout::get('main') #6 /home/dignity/local_projects/demo/index.php(20): Flexi\Routing\Router::initialize() #7 {main} thrown in /home/dignity/local_projects/demo/flexi/Template/Component.php on line 56`

**Comment by artemmelnik** [comment]
Thank you! I will correct it within 2 days

**Comment by dignityinside** [comment]
What's about bug fix? :)

**Comment by artemmelnik** [comment]
Fix. Also added twig
