### ISSUE TITLE
Active theme "dadstudio" not found

### ISSUE THREAD

**Issue by dignityinside** [artemmelnik/flexicms#19]
`Fatal error: Uncaught Exception: View file <strong>/home/dignity/local_projects/demo/content/themes/dadstudio/main.layout.phtml</strong> does not exist! in /home/dignity/local_projects/demo/flexi/Template/Component.php:56 Stack trace: #0 /home/dignity/local_projects/demo/flexi/Template/Layout.php(60): Flexi\Template\Component::load('/home/dignity/l...', Array) #1 /home/dignity/local_projects/demo/flexi/Routing/Router.php(71): Flexi\Template\Layout::get('main') #2 /home/dignity/local_projects/demo/index.php(20): Flexi\Routing\Router::initialize() #3 {main} thrown in /home/dignity/local_projects/demo/flexi/Template/Component.php on line 56`

There is no such themes. Probably an error in "setting" table in flexicms.sql

**Comment by artemmelnik** [comment]
I plan to implement the twig template

**Comment by artemmelnik** [comment]
Change the value in the database, table setting
