### ISSUE TITLE
Error in QueryBuilder.php

### ISSUE THREAD

**Issue by tirilo555** [artemmelnik/flexicms#2]
http://prntscr.com/gt4v5z
http://prntscr.com/gt4w59

**Comment by artemmelnik** [comment]
спасибо за обращение. Пришлите пожалуйста место где вызывается метод set

**Comment by Natalivk** [comment]
Спасибо за ответ, после того как Вы обновили файлы все нормально работает!
Еще раз спасибо и за вашу работу!

04 окт. 2017 г. 15:54 пользователь "Artem Melnik" <notifications@github.com>
написал:

**Comment by VegaDey** [comment]
http://flexi.loc/admin/settings/general/

Пропали настройки

**Comment by tirilo555** [comment]
artemmelnik, на скрине видно что  это произошло при ауторизации. после этого я удалил точку в указаном на втором скрине  месте.

**Comment by artemmelnik** [comment]
Исправлено.
