### ISSUE TITLE
Проблема с функцией path

### ISSUE THREAD

**Issue by dcherkasov** [artemmelnik/flexicms#24]
Warning: scandir(/home/kryptikk/workspace/**app**modules): failed to open dir: No such file or directory in /home/kryptikk/workspace/app/flexi/Routing/Router.php on line 80

Исправляется добавлением слэшей в функцию path, как указано на скрине:
![screenshot_2018-08-12_19-40-51](https://user-images.githubusercontent.com/32767271/44004215-a92f8566-9e67-11e8-87b8-7cb2e9b589f4.png)

**Comment by artemmelnik** [comment]
Готово
