### ISSUE TITLE
Помилка при встановленні

### ISSUE THREAD

**Issue by dymydm** [artemmelnik/flexicms#31]
Fatal error: Uncaught Exception: could not find driver in D:\openserver\OSPanel\domains\flexicms-master\flexi\Database\Database.php:85 Stack trace: #0 D:\openserver\OSPanel\domains\flexicms-master\flexi\Database\Database.php(39): Flexi\Database\Database::connect() #1 D:\openserver\OSPanel\domains\flexicms-master\flexi\Flexi.php(48): Flexi\Database\Database::initialize() #2 D:\openserver\OSPanel\domains\flexicms-master\flexi\Routing\Router.php(38): Flexi\Flexi::start() #3 D:\openserver\OSPanel\domains\flexicms-master\index.php(24): Flexi\Routing\Router::initialize() #4 {main} thrown in D:\openserver\OSPanel\domains\flexicms-master\flexi\Database\Database.php on line 85

**Comment by dymydm** [comment]
Как установить cms?

**Comment by artemmelnik** [comment]
Добрый день
У вас скорее всего нет подключения к бд
Могу помочь за небольшое вознаграждение )

вт, 27 нояб. 2018 г. в 15:08, dymydm <notifications@github.com>:

**Comment by artemmelnik** [comment]
Вам нужно придерживаться инструкции.
