### ISSUE TITLE
Проект умер?

### ISSUE THREAD

**Issue by ZeoNish** [artemmelnik/flexicms#32]
Можно попросить хотя бы базу данных нормальную, а то ошибки выбивает что в БД не хватает таблиц

**Comment by artemmelnik** [comment]
да конечно, сделаю на выходных

**Comment by ZeoNish** [comment]
> да конечно, сделаю на выходных

Ой спасибо

**Comment by ZeoNish** [comment]
> да конечно, сделаю на выходных

Артем. Забыл?

**Comment by artemmelnik** [comment]
Нет, сегодня вечером будет!

**Comment by artemmelnik** [comment]
залил дамп, проверьте

**Comment by ZeoNish** [comment]
> залил дамп, проверьте

Спасибо. 
Но вот :-) http://prntscr.com/n6c3vn

**Comment by ZeoNish** [comment]
:-) Нельзя забрасывать проект. Хорошая ведь могла бы получиться CMS

**Comment by artemmelnik** [comment]
Ага, нужно таблицы связей залить.

**Comment by artemmelnik** [comment]
Нет поддержки, никто не пользуется )

**Comment by ZeoNish** [comment]
> Нет поддержки, никто не пользуется )

ну просто чуть больше функционала и несколько модулей :-)

**Comment by ZeoNish** [comment]
А мне понравился проект. Его бы допилить и было бы отлично. Засунуть удобства по максимуму что бы было удобно разрабатывать модули и все было бы хорошо.

**Comment by ZeoNish** [comment]
Я бы тебе посоветовал не забрасывать проект, а доделать его до годного состояния.
Если в нем будет какая ни какая автоматизация и удобство разработки модулей то и сообществом от начнет обрастать быстро :-)

**Comment by ZeoNish** [comment]
Было бы круто если модули были полностью самостоятельны (ну все части модуля лежали в одной папке) и был базовый набор функций.
