### ISSUE TITLE
Fatal error: Uncaught Exception: Cannot load config from file, file C:/xampp/htdocs\config\database.php does not exist

### ISSUE THREAD

**Issue by ArtMin96** [artemmelnik/flexicms#33]
When I run the code I got problem with configs. The problem actually coming from Config/Config.php
line: 55 code: 
`$path = $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . $group . '.php';
print_r($path);die;`

Output: C:/xampp/htdocs\missing_url\config\database.php

Try to run localhost/flexicms/

**Comment by ArtMin96** [comment]
Also, the database is not complete.

`MySQL Error`
`Table 'db.resource_type_relation' doesn't exist`
`Last Query`
`SELECT rt.* FROM resource_type as rt JOIN resource_type_relation as rtr ON rt.id = rtr.resource_type_to_id WHERE rtr.resource_type_id = 1`

**Comment by ArtMin96** [comment]
But cms looks good. Good job!

**Comment by artemmelnik** [comment]
> But cms looks good. Good job!

Thank! reanimating db

**Comment by artemmelnik** [comment]
> But cms looks good. Good job!

Fixed!
