### ISSUE TITLE
Git Bash error when executing db:import

### ISSUE THREAD

**Issue by MaBaOMSI** [artemmelnik/flexicms#34]
I got this error when trying to execute db:import with terminal: Cannot load config from file, file <strong>/c/xampp/htdocs/flexi\config\database.php</strong> does not exist.
 What to do?

**Comment by artemmelnik** [comment]
try to browse the file paths

**Comment by artemmelnik** [comment]
> I got this error when trying to execute db:import with terminal: Cannot load config from file, file **/c/xampp/htdocs/flexi\config\database.php** does not exist.
> What to do?

try to browse the file paths, otherwise
